// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC603fbyMl4RR-DNHWxZf6fkdBhWnEi1uI',
    appId: '1:566059116325:web:53feb5c604b822c8ca1ccc',
    messagingSenderId: '566059116325',
    projectId: 'car-pool-8c38c',
    authDomain: 'car-pool-8c38c.firebaseapp.com',
    databaseURL: 'https://car-pool-8c38c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'car-pool-8c38c.appspot.com',
    measurementId: 'G-PXNF8NE6M7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBetmibwHrG7KAq74b7sujh7McwvGyz-rY',
    appId: '1:566059116325:android:5f6e83d06d2f1287ca1ccc',
    messagingSenderId: '566059116325',
    projectId: 'car-pool-8c38c',
    databaseURL: 'https://car-pool-8c38c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'car-pool-8c38c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7G3H-XloZHXDRGCj68_UcsmLg_w2VPOw',
    appId: '1:566059116325:ios:cd2efb95bf9ae0d0ca1ccc',
    messagingSenderId: '566059116325',
    projectId: 'car-pool-8c38c',
    databaseURL: 'https://car-pool-8c38c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'car-pool-8c38c.appspot.com',
    iosBundleId: 'com.example.carPool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7G3H-XloZHXDRGCj68_UcsmLg_w2VPOw',
    appId: '1:566059116325:ios:c96fb46b9f4c7d9eca1ccc',
    messagingSenderId: '566059116325',
    projectId: 'car-pool-8c38c',
    databaseURL: 'https://car-pool-8c38c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'car-pool-8c38c.appspot.com',
    iosBundleId: 'com.example.carPool.RunnerTests',
  );
}
